spring:
  application:
    name:
      demo
  datasource:
    url: jdbc:mysql://localhost:3306/db?createDatabaseIfNotExist=true
    username: user
    password: password
  sql:
    init:
      mode: always
doma:
  dialect: mysql

aws:
  access-key-id: test
  secret-key: test
  region: ap-northeast-1
  s3:
    endpoint: http://localhost:4566